snapshots:
  - name: products_snapshot
    relation: source('landing', 'products')
    config:
      schema: bronze
      unique_key: id
      strategy: timestamp
      updated_at: created_at
    columns:
      - name: id
        data_tests:
          - unique:
              config:
                where: "dbt_valid_to is null"
                severity: warn